# Generated by Django 2.2 on 2021-06-26 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cantidad', '0001_initial'),
        ('productos', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantidad',
            name='id_orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_cantidad', to='pedidos.Pedidos'),
        ),
        migrations.AddField(
            model_name='cantidad',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_producto', to='productos.Productos'),
        ),
    ]
