# Generated by Django 2.2 on 2021-06-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_creacion',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
