# Generated by Django 2.2 on 2021-06-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20210626_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
