# Generated by Django 2.2 on 2021-06-26 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20210626_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
