# Generated by Django 2.2 on 2021-06-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(default='nn', max_length=100),
            preserve_default=False,
        ),
    ]
